[package]
name = "restqs-sqlite-tests"
version = "0.0.0"
edition = "2024"
rust-version = "1.85"
publish = false

[dependencies]
restqs = { path = "../..", features = ["sqlx"] }
sqlx = { version = "=0.8.6", default-features = false, features = ["sqlite", "runtime-tokio"] }
tokio = { version = "1", features = ["rt"] }

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
missing_docs_in_private_items = "deny"
expect_used = "deny"
panic = "deny"
unwrap_used = "deny"
